// Title - used in Patient Profile
export const TITLE_DATA = [
  { value: "Mr", label: "Mr" },
  { value: "Mrs", label: "Mrs" },
  { value: "Chief", label: "Chief" },
  { value: "Prof", label: "Prof" },
  { value: "Dr", label: "Dr" },
  { value: "Honorable", label: "Honorable" },
  { value: "Mzee", label: "Mzee" },
  { value: "Bi", label: "Bi" },
  { value: "Miss", label: "Miss" },
  { value: "Master", label: "Master" },
  { value: "Madam", label: "Madam" },
  { value: "Senator", label: "Senator" },
  { value: "President", label: "President" },
  { value: "Speaker", label: "Speaker" },
  { value: "Councilor", label: "Councilor" },
  { value: "Governor", label: "Governor" },
  { value: "Ambassador", label: "Ambassador" },
  { value: "Bishop", label: "Bishop" },
  { value: "Mayor", label: "Mayor" },
  { value: "Engr.", label: "Engr." },
  { value: "Surv", label: "Surv" },
  { value: "Dr. Alhaja Chief", label: "Dr. Alhaja Chief" },
  { value: "Alhaja", label: "Alhaja" },
  { value: "Chief Dr.", label: "Chief Dr." },
  { value: "Eze", label: "Eze" },
  { value: "Igwe", label: "Igwe" },
  { value: "Oba", label: "Oba" },
  { value: "Alhaji", label: "Alhaji" },
  { value: "Sir", label: "Sir" },
  { value: "Dr. (Mrs)", label: "Dr. (Mrs)" },
  { value: "Dr. (Mr)", label: "Dr. (Mr)" },
  { value: "Alhaja Pharm Mrs", label: "Alhaja Pharm Mrs" },
  { value: "Engr. Double Chief Sir", label: "Engr. Double Chief Sir" },
  { value: "Chief Dr. Sir", label: "Chief Dr. Sir" },
  { value: "Distinguished Senator", label: "Distinguished Senator" },
  { value: "Honorable Speaker.", label: "Honorable Speaker." },
  { value: "His Excellency", label: "His Excellency" },
  { value: "Pharm. Chief (Mrs.)", label: "Pharm. Chief (Mrs.)" },
];

// Martial Status - used in Patient Profile
export const MARITAL_STATUS_DATA = [
  { value: "Married", label: "Married" },
  { value: "Single", label: "Single" },
  { value: "Divorced", label: "Divorced" },
  { value: "Engaged", label: "Engaged" },
];

// Blood types - used in Patient Profile
export const BLOOD_TYPES_DATA = [
  { value: "I dont know", label: "i-dont-know" },
  { value: "A+", label: "A+" },
  { value: "A-", label: "A-" },
  { value: "B+", label: "B+" },
  { value: "B-", label: "B-" },
  { value: "O+", label: "O+" },
  { value: "O-", label: "O-" },
  { value: "AB+", label: "AB+" },
  { value: "AB-", label: "AB-" },
];

// Height in cm - used in Patient Profile
export const PATIENT_CHILD_HEIGHT = [
  { value: 20, label: "20cm" },
  { value: 50, label: "50cm" },
  { value: 70, label: "70cm" },
  { value: 100, label: "100cm" },
  { value: 120, label: "120cm" },
  { value: 150, label: "150cm" },
  { value: 170, label: "170cm" },
  { value: 200, label: "200cm" },
  { value: 220, label: "220cm" },
  { value: 250, label: "250cm" },
];

// Wight in kg - used in Patient Profile
export const PATIENT_WEIGHT = [
  { value: 100, label: "100kg" },
  { value: 200, label: "200kg" },
  { value: 300, label: "300kg" },
  { value: 400, label: "400kg" },
];

// Wight in kg - used in Patient Profile
export const PATIENT_CHILD_WEIGHT = [
  { value: 1, label: "1kg" },
  { value: 50, label: "50kg" },
  { value: 100, label: "100kg" },
  { value: 150, label: "150kg" },
  { value: 200, label: "200kg" },
];

// Preferred Language - used in Patient Profile
export const PREFERRED_LANGUAGE = [
  { value: "Za", label: "Afrikaans" },
  { value: "Gh", label: "Akan" },
  { value: "En", label: "English" },
  { value: "Ew", label: "Ewa" },
  { value: "Fr", label: "French" },
  { value: "De", label: "German" },
  { value: "Ha", label: "Hausa" },
  { value: "Ig", label: "Igo" },
  { value: "Pt", label: "Portuguese" },
  { value: "Es", label: "Spanish" },
  { value: "Sw", label: "Swahili" },
  { value: "Sv", label: "Swedish" },
  { value: "Yo", label: "Yoruba" },
];
//  Languages - used in Patient Profile
export const LANGUAGES_NIGERIA = [
  { value: "English", label: "English" },
  { value: "Pidgin English", label: "Pidgin English" },
  { value: "Igbo", label: "Igbo" },
  { value: "Hausa", label: "Hausa" },
  { value: "Yoruba", label: "Yoruba" },
];

export const LANGUAGES_NAMIBIA = [
  { value: "English", label: "English" },
  { value: "Oshiwambo", label: "Oshiwambo" },
  { value: "Khoekhoegowab    ", label: "Khoekhoegowab" },
  { value: "Otjiherero", label: "Otjiherero" },
  { value: "RuKwangali", label: "RuKwangali" },
  { value: "siLozi", label: "siLozi" },
  { value: "German", label: "German" },
  { value: "San", label: "San" },
];

export const LANGUAGES_TANZANIA = [
  { value: "English", label: "English" },
  { value: "Swahili", label: "Swahili" },
  { value: "Nyamwezi", label: "Nyamwezi" },
  { value: "Sukuma", label: "Sukuma" },
  { value: "Hehe", label: "Hehe" },
  { value: "Chagga", label: "Chagga" },
  { value: "Haya", label: "Haya" },
  { value: "Gogo", label: "Gogo" },
  { value: "Makonde", label: "Makonde" },
  { value: "Ha", label: "Ha" },
];

export const LANGUAGES_GHANA = [
  { value: "English", label: "English" },
  { value: "Akan", label: "Akan" },
  { value: "Ewe", label: "Ewe" },
  { value: "Dagabani", label: "Dagabani" },
  { value: "Dangme", label: "Dangme" },
  { value: "Ga", label: "Ga" },
  { value: "Nzema", label: "Nzema" },
  { value: "Gonja", label: "Gonja" },
  { value: "Kasem", label: "Kasem" },
  { value: "Pidgin", label: "Pidgin" },
];

export const LANGUAGES_RWANDA = [
  { value: "English", label: "English" },
  { value: "Kinyarwanda", label: "Kinyarwanda" },
  { value: "French", label: "French" },
  { value: "Swahili", label: "Swahili" },
];

// Country Data  - used in Patient Profile
export const COUNTRY = [
  { value: "Ghana", label: "Ghana" },
  { value: "Nigeria", label: "Nigeria" },
  { value: "Tanzania", label: "Tanzania" },
  { value: "Rwanda", label: "Rwanda" },
  { value: "Namibia", label: "Namibia" },
];
//state Data for Rawanda
export const STATE_RWANDA = [
  {
    value: "Eastern Province",
    label: "Eastern Province",
    cities: ["Kibungo", "Rwamagana"],
  },
  {
    value: "Kigali districte",
    label: "Kigali districte",
    cities: ["Kigali"],
  },
  {
    value: "Northern Province",
    label: "Northern Province",
    cities: ["Byumba", "Musanze"],
  },
  {
    value: "Southern Province",
    label: "Southern Province",
    cities: ["Butare", "Eglise Catholique Centrale GIKO", "Gitarama", "Nzega"],
  },
  {
    value: "Western Province",
    label: "Western Province",
    cities: ["Cyangugu", "Gisenyi", "Kibuye"],
  },
];

// State Data for Nigeria  - used in Patient Profile
export const STATE_NIGERIA = [
  {
    value: "Abuja Federal Capital Territory",
    label: "Abuja Federal Capital Territory",
    cities: ["Abuja", "Kuje", "Kwali", "Madala"],
  },
  {
    value: "Adamawa",
    label: "Adamawa",
    cities: [
      "Ganye",
      "Gombi",
      "Holma",
      "Jimeta",
      "Madagali",
      "Mayo-Belwa",
      "Mubi",
      "Ngurore",
      "Numan",
      "Toungo",
      "Yola",
    ],
  },
  {
    value: "Akwa Ibom",
    label: "Akwa Ibom",
    cities: ["Eket", "Esuk Oron", "Ikot Ekpene", "Itu", "Uyo"],
  },
  {
    value: "Anambra",
    label: "Anambra",
    cities: [
      "Agulu",
      "Atani",
      "Awka",
      "Enugu-Ukwu",
      "Igbo-Ukwu",
      "Ihiala",
      "Nkpor",
      "Nnewi",
      "Onitsha",
      "Ozubulu",
      "Uga",
      "Uruobo-Okija",
    ],
  },
  {
    value: "Bauchi",
    label: "Bauchi",
    cities: [
      "Azare",
      "Bauchi",
      "Boi",
      "Bununu",
      "Darazo",
      "Dass",
      "Dindima",
      "Disina",
      "Gabarin",
      "Gwaram",
      "Kari",
      "Lame",
      "Lere",
      "Madara",
      "Misau",
      "Sade",
      "Yamrat",
      "Yanda Bayo",
      "Yuli",
      "Zadawa",
      "Zalanga",
    ],
  },
  {
    value: "Bayelsa",
    label: "Bayelsa",
    cities: ["Amassoma", "Twon-Brass", "Yenagoa"],
  },
  {
    value: "Benue",
    label: "Benue",
    cities: [
      "Aliade",
      "Boju",
      "Gboko",
      "Igbor",
      "Makurdi",
      "Ochobo",
      "Otukpa",
      "Takum",
      "Ugbokpo",
      "Yandev",
      "Zaki Biam",
    ],
  },
  {
    value: "Borno",
    label: "Borno",
    cities: [
      "Bama",
      "Benisheikh",
      "Biu",
      "Bornu Yassu",
      "Damasak",
      "Damboa",
      "Dikwa",
      "Gamboru",
      "Gwoza",
      "Kukawa",
      "Magumeri",
      "Maiduguri",
      "Marte",
      "Miringa",
      "Monguno",
      "Ngala",
      "Shaffa",
      "Shani",
      "Tokombere",
      "Uba",
      "Wuyo",
      "Yajiwa",
    ],
  },
  {
    value: "Cross_River",
    label: "Cross River",
    cities: ["Akankpa", "Calabar", "Gakem", "Ikang", "Ugep"],
  },
  {
    value: "Delta",
    label: "Delta",
    cities: [
      "Abraka",
      "Agbor",
      "Asaba",
      "Bomadi",
      "Burutu",
      "Kwale",
      "Obiaruku",
      "Ogwashi-Uku",
      "Orerokpe",
      "Patani",
      "Sapele",
      "Ughelli",
      "Umunede",
      "Warri",
    ],
  },
  {
    value: "Ebonyi",
    label: "Ebonyi",
    cities: ["Abakaliki", "Afikpo", "Effium", "Ezza-Ohu", "Isieke"],
  },
  {
    value: "Edo",
    label: "Edo",
    cities: [
      "Agenebode",
      "Auchi",
      "Benin City",
      "Ekpoma",
      "Igarra",
      "Illushi",
      "Siluko",
      "Ubiaja",
      "Uromi",
    ],
  },
  {
    value: "Ekiti",
    label: "Ekiti",
    cities: [
      "Ado-Ekiti",
      "Aramoko-Ekiti",
      "Efon-Alaaye",
      "Emure-Ekiti",
      "Ifaki",
      "Igbara-Odo",
      "Igede-Ekiti",
      "Ijero-Ekiti",
      "Ikere-Ekiti",
      "Ipoti",
      "Ise-Ekiti",
      "Oke Ila",
      "Omuo-Ekiti",
    ],
  },
  {
    value: "Enugu",
    label: "Enugu",
    cities: [
      "Adani",
      "Ake-Eze",
      "Aku",
      "Amagunze",
      "Awgu",
      "Eha Amufu",
      "Enugu",
      "Enugu-Ezike",
      "Ete",
      "Ikem",
      "Mberubu",
      "Nsukka",
      "Obolo-Eke (1)",
      "Opi",
      "Udi",
    ],
  },
  {
    value: "Gombe",
    label: "Gombe",
    cities: [
      "Akko",
      "Bara",
      "Billiri",
      "Dadiya",
      "Deba",
      "Dukku",
      "Garko",
      "Gombe",
      "Hinna",
      "Kafarati",
      "Kaltungo",
      "Kumo",
      "Nafada",
      "Pindiga",
    ],
  },
  {
    value: "Imo",
    label: "Imo",
    cities: ["Iho", "Oguta", "Okigwe", "Orlu", "Orodo", "Owerri"],
  },
  {
    value: "Jigawa",
    label: "Jigawa",
    cities: [
      "Babura",
      "Birnin Kudu",
      "Birniwa",
      "Dutse",
      "Gagarawa",
      "Gumel",
      "Gwaram",
      "Hadejia",
      "Kafin Hausa",
      "Kazaure",
      "Kiyawa",
      "Mallammaduri",
      "Ringim",
      "Samamiya",
    ],
  },
  {
    value: "Kaduna",
    label: "Kaduna",
    cities: [
      "Anchau",
      "Burumburum",
      "Dutsen Wai",
      "Hunkuyi",
      "Kachia",
      "Kaduna",
      "Kafanchan",
      "Kagoro",
      "Kajuru",
      "Kujama",
      "Lere",
      "Mando",
      "Saminaka",
      "Soba",
      "Sofo-Birnin-Gwari",
      "Zaria",
    ],
  },
  { value: "Kano", label: "Kano", cities: ["Dan Gora", "Gaya", "Kano"] },
  {
    value: "Katsina",
    label: "Katsina",
    cities: [
      "Danja",
      "Dankama",
      "Daura",
      "Dutsin-Ma",
      "Funtua",
      "Gora",
      "Jibia",
      "Jikamshi",
      "Kankara",
      "Katsina",
      "Mashi",
      "Ruma",
      "Runka",
      "Wagini",
    ],
  },
  {
    value: "Kebbi",
    label: "Kebbi",
    cities: [
      "Argungu",
      "Bagudo",
      "Bena",
      "Bin Yauri",
      "Birnin Kebbi",
      "Dabai",
      "Dakingari",
      "Gulma",
      "Gwandu",
      "Jega",
      "Kamba",
      "Kangiwa",
      "Kende",
      "Mahuta",
      "Maiyama",
      "Shanga",
      "Wasagu",
      "Zuru",
    ],
  },
  {
    value: "Kogi",
    label: "Kogi",
    cities: [
      "Abocho",
      "Adoru",
      "Ankpa",
      "Bugana",
      "Dekina",
      "Egbe",
      "Icheu",
      "Idah",
      "Isanlu-Itedoijowa",
      "Kabba",
      "Koton-Karfe",
      "Lokoja",
      "Ogaminana",
      "Ogurugu",
      "Okene",
    ],
  },
  {
    value: "Kwara",
    label: "Kwara",
    cities: [
      "Ajasse Ipo",
      "Bode Saadu",
      "Gwasero",
      "Ilorin",
      "Jebba",
      "Kaiama",
      "Lafiagi",
      "Offa",
      "Okuta",
      "Omu-Aran",
      "Patigi",
      "Suya",
      "Yashikera",
    ],
  },
  {
    value: "Lagos",
    label: "Lagos",
    cities: [
      "Apapa",
      "Badagry",
      "Ebute Ikorodu",
      "Ejirin",
      "Epe",
      "Ikeja",
      "Lagos",
      "Makoko",
    ],
  },
  {
    value: "Nasarawa",
    label: "Nasarawa",
    cities: ["Buga", "Doma", "Keffi", "Lafia", "Nasarawa", "Wamba"],
  },
  {
    value: "Niger",
    label: "Niger",
    cities: [
      "Auna",
      "Babana",
      "Badeggi",
      "Baro",
      "Bokani",
      "Duku",
      "Ibeto",
      "Konkwesso",
      "Kontagora",
      "Kusheriki",
      "Kuta",
      "Lapai",
      "Minna",
      "New Shagunnu",
      "Suleja",
      "Tegina",
      "Ukata",
      "Wawa",
      "Zungeru",
    ],
  },
  {
    value: "Ogun",
    label: "Ogun",
    cities: [
      "Abeokuta",
      "Ado Odo",
      "Idi Iroko",
      "Ifo",
      "Ijebu-Ife",
      "Ijebu-Igbo",
      "Ijebu-Ode",
      "Ilaro",
      "Imeko",
      "Iperu",
      "Isara",
      "Owode",
    ],
  },
  {
    value: "Ondo",
    label: "Ondo",
    cities: [
      "Agbabu",
      "Akure",
      "Idanre",
      "Ifon",
      "Ilare",
      "Ode",
      "Ondo",
      "Ore",
      "Owo",
    ],
  },
  {
    value: "Osun",
    label: "Osun",
    cities: [
      "Apomu",
      "Ejigbo",
      "Gbongan",
      "Ijebu-Jesa",
      "Ikire",
      "Ikirun",
      "Ila Orangun",
      "Ile-Ife",
      "Ilesa",
      "Ilobu",
      "Inisa",
      "Iwo",
      "Modakeke",
      "Oke Mesi",
      "Olupona",
      "Osogbo",
      "Otan Ayegbaju",
      "Oyan",
    ],
  },
  {
    value: "Oyo",
    label: "Oyo",
    cities: [
      "Ago Are",
      "Alapa",
      "Fiditi",
      "Ibadan",
      "Igbeti",
      "Igbo-Ora",
      "Igboho",
      "Kisi",
      "Lalupon",
      "Ogbomoso",
      "Okeho",
      "Orita Eruwa",
      "Oyo",
      "Saki",
    ],
  },
  {
    value: "Plateau",
    label: "Plateau",
    cities: [
      "Amper",
      "Bukuru",
      "Dengi",
      "Jos",
      "Kwolla",
      "Langtang",
      "Pankshin",
      "Panyam",
      "Vom",
      "Yelwa",
    ],
  },
  {
    value: "Rivers",
    label: "Rivers",
    cities: [
      "Abalama",
      "Abonnema",
      "Ahoada",
      "Bori",
      "Buguma",
      "Chokocho",
      "Elele",
      "Obonoma",
      "Omoku",
      "Onne",
      "Opobo",
      "Port Harcourt",
      "Rumuokoro",
    ],
  },
  {
    value: "Sokoto",
    label: "Sokoto",
    cities: [
      "Binji",
      "Dange",
      "Gandi",
      "Goronyo",
      "Gwadabawa",
      "Illela",
      "Rabah",
      "Sokoto",
      "Tambuwal",
      "Wurno",
    ],
  },
  {
    value: "Taraba",
    label: "Taraba",
    cities: [
      "Baissa",
      "Beli",
      "Gassol",
      "Gembu",
      "Ibi",
      "Jalingo",
      "Lau",
      "Mutum Biyu",
      "Riti",
      "Wukari",
    ],
  },
  {
    value: "Yobe",
    label: "Yobe",
    cities: [
      "Damaturu",
      "Dankalwa",
      "Dapchi",
      "Daura",
      "Fika",
      "Gashua",
      "Geidam",
      "Goniri",
      "Gorgoram",
      "Gujba",
      "Gwio Kura",
      "Kumagunnam",
      "Lajere",
      "Machina",
      "Nguru",
      "Potiskum",
    ],
  },
  {
    value: "Zamfara",
    label: "Zamfara",
    cities: [
      "Anka",
      "Dan Sadau",
      "Gummi",
      "Gusau",
      "Kaura Namoda",
      "Kwatarkwashi",
      "Maru",
      "Moriki",
      "Sauri",
      "Tsafe",
    ],
  },
];

// State Data for Tanzania  - used in Patient Profile
export const STATE_TANZANIA = [
  {
    value: "Arusha",
    label: "Arusha",
    cities: [
      "Arusha",
      "Kingori",
      "Kiratu",
      "Longido",
      "Mbuguni",
      "Merelani",
      "Meru",
      "Monduli",
      "Mto wa Mbu",
      "Namanga",
      "Ngorongoro",
      "Nkoaranga",
      "Poli",
      "Usa River",
    ],
  },
  {
    value: "Dar es Salaam",
    label: "Dar es Salaam",
    cities: ["Dar es Salaam", "Magomeni"],
  },
  {
    value: "Dodoma",
    label: "Dodoma",
    cities: [
      "Dodoma",
      "Kibakwe",
      "Kisasa",
      "Kondoa",
      "Kongwa",
      "Mpwapwa",
      "Msanga",
    ],
  },
  {
    value: "Geita",
    label: "Geita",
    cities: [
      "Buseresere",
      "Chato",
      "Geita",
      "Kasamwa",
      "Katoro",
      "Masumbwe",
      "Ushirombo",
      "Uyovu",
    ],
  },
  {
    value: "Iringa",
    label: "Iringa",
    cities: ["Ilula", "Iringa", "Izazi", "Mafinga", "Makungu", "Malangali"],
  },
  {
    value: "Kagera",
    label: "Kagera",
    cities: [
      "Biharamulo",
      "Bugarama",
      "Bugene",
      "Bukoba",
      "Kabanga",
      "Kamachumu",
      "Katerero",
      "Katoro",
      "Kyaka",
      "Ngara",
      "Nshamba",
      "Nsunga",
      "Nyakahanga",
      "Rulenge",
    ],
  },
  {
    value: "Katavi",
    label: "Katavi",
    cities: ["Inyonga", "Karema", "Mpanda", "Usevia"],
  },
  {
    value: "Kigoma",
    label: "Kigoma",
    cities: [
      "Kakonko",
      "Kasulu",
      "Kibondo",
      "Kigoma",
      "Mabamba",
      "Mwandiga",
      "Nguruka",
      "Uvinza",
    ],
  },
  {
    value: "Kilimanjaro",
    label: "Kilimanjaro",
    cities: [
      "Hedaru",
      "Kihurio",
      "Kisiwani",
      "Kwakoa",
      "Lembeni",
      "Makanya",
      "Moshi",
      "Mwembe",
      "Ndungu",
      "Same",
    ],
  },
  {
    value: "Lindi",
    label: "Lindi",
    cities: [
      "Lindi",
      "Mbekenyera",
      "Mingoyo",
      "Mtama",
      "Nachingwea",
      "Nyangao",
      "Ruangwa",
    ],
  },
  {
    value: "Manyara",
    label: "Manyara",
    cities: [
      "Babati",
      "Bashanet",
      "Basotu",
      "Dareda",
      "Dongobesh",
      "Endasak",
      "Galappo",
      "Katesh",
      "Kibaya",
      "Kirya",
      "Magugu",
      "Mbulu",
      "Naberera",
      "Nangwa",
    ],
  },
  {
    value: "Mara",
    label: "Mara",
    cities: [
      "Bukonyo",
      "Butiama",
      "Issenye",
      "Kibara",
      "Mugango",
      "Mugumu",
      "Muriti",
      "Musoma",
      "Nakatunguru",
      "Nansio",
      "Nyamuswa",
      "Sirari",
    ],
  },
  {
    value: "Mbeya",
    label: "Mbeya",
    cities: [
      "Chimala",
      "Hedaru",
      "Ibaba",
      "Ikama",
      "Ikinga",
      "Ikolo",
      "Ikuti",
      "Ilembo",
      "Ipinda",
      "Kabula",
      "Kahe Tanzania",
      "Kandete",
      "Katumba",
      "Kihurio",
      "Kisiwani",
      "Kiwira",
      "Kwakoa",
      "Lembeni",
      "Lupata",
      "Lusungo",
      "Machame",
      "Makanya",
      "Marangu",
      "Masukulu",
      "Mbeya",
      "Mlowo",
      "Moshi",
      "Mpuguso",
      "Mwansanga",
      "Mwaya",
      "Mwembe",
      "Same",
      "Tukuyu",
      "Tunduma",
      "Ugweno",
      "Ulanga",
    ],
  },
  {
    value: "Morogoro",
    label: "Morogoro",
    cities: [
      "Geiro",
      "Ifakara",
      "Kidatu",
      "Kidodi",
      "Kilosa",
      "Kimamba",
      "Kisanga",
      "Lupiro",
      "Magole",
      "Mahenge",
      "Malinyi",
      "Mikumi",
      "Mlimba",
      "Morogoro",
      "Msowero",
      "Mtimbira",
      "Mvomero District",
      "Ngerengere",
    ],
  },
  {
    value: "Mtwara",
    label: "Mtwara",
    cities: [
      "Chiungutwa",
      "Kitama",
      "Kitangari",
      "Luchingu",
      "Lukuledi",
      "Lulindi",
      "Madimba",
      "Mahuta",
      "Masasi",
      "Masuguru",
      "Mtwara",
      "Namalenga",
      "Namikupa",
      "Nanganga",
      "Nangomba",
      "Nanhyanga",
      "Nanyamba",
      "Newala Kisimani",
      "Tandahimba",
    ],
  },
  {
    value: "Mwanza",
    label: "Mwanza",
    cities: [
      "Ilemela District",
      "Kihangara",
      "Malya",
      "Misasi",
      "Misungwi",
      "Mwanza",
      "Ngudu",
      "Nyanguge",
      "Usagara",
    ],
  },
  {
    value: "Njombe",
    label: "Njombe",
    cities: [
      "Ilembula",
      "Makumbako",
      "Manda",
      "Matamba",
      "Mlangali",
      "Mtwango",
      "Njombe",
    ],
  },
  {
    value: "Pemba North",
    label: "Pemba North",
    cities: ["Konde", "Micheweni", "Wete"],
  },
  {
    value: "Pemba South",
    label: "Pemba South",
    cities: ["Chake Chake", "Mtambile", "Uwelini"],
  },
  {
    value: "Pwani",
    label: "Pwani",
    cities: [
      "Bagamoyo",
      "Bungu",
      "Chalinze",
      "Ikwiriri",
      "Kibaha",
      "Kibiti",
      "Kilindoni",
      "Kisarawe",
      "Lugoba",
      "Maneromango",
      "Mbumi",
      "Mkuranga",
      "Mlandizi",
      "Mvomero",
      "Utete",
      "Vikindu",
    ],
  },
  {
    value: "Rukwa",
    label: "Rukwa",
    cities: [
      "Chala",
      "Kirando",
      "Laela",
      "Matai",
      "Namanyere",
      "Nkove",
      "Sumbawanga",
    ],
  },
  {
    value: "Ruvuma",
    label: "Ruvuma",
    cities: [
      "Kigonsera",
      "Liuli",
      "Mahanje",
      "Maposeni",
      "Matiri",
      "Mbamba Bay",
      "Mbinga",
      "Songea",
      "Tingi",
    ],
  },
  {
    value: "Shinyanga",
    label: "Shinyanga",
    cities: [
      "Isaka",
      "Kahama",
      "Kishapu",
      "Mhango",
      "Mwadui",
      "Old Shinyanga",
      "Shinyanga",
      "Songwa",
      "Tinde",
    ],
  },
  {
    value: "Simiyu",
    label: "Simiyu",
    cities: [
      "Bariadi",
      "Kisesa",
      "Lalago",
      "Malampaka",
      "Maswa",
      "Matonga",
      "Nyakabindi",
      "Nyalikungu",
      "Somanda",
    ],
  },
  {
    value: "Singida",
    label: "Singida",
    cities: [
      "Igugunu",
      "Ikungi",
      "Ilongero",
      "Itigi",
      "Kilimatinde",
      "Kintinku",
      "Kiomboi",
      "Mgandu",
      "Mtinko",
      "Mungaa",
      "Ndago",
      "Puma",
      "Sepuka",
      "Shelui",
      "Singida",
    ],
  },
  { value: "Songwe", label: "Songwe", cities: [] },
  {
    value: "Tabora",
    label: "Tabora",
    cities: [
      "Bukene",
      "Igurubi",
      "Kaliua",
      "Mabama",
      "Sikonge",
      "Tabora",
      "Tumbi",
      "Usoke",
    ],
  },
  {
    value: "Tanga",
    label: "Tanga",
    cities: [
      "Chanika",
      "Lushoto",
      "Magomeni",
      "Majengo",
      "Makuyuni",
      "Maramba",
      "Matui",
      "Mazinde",
      "Mlalo",
      "Muheza",
      "Mwanga",
      "Pangani",
      "Soni",
      "Tanga",
    ],
  },
  {
    value: "Zanzibar North",
    label: "Zanzibar North",
    cities: ["Gamba", "Kijini", "Kiwengwa", "Mkokotoni", "Nungwi"],
  },
  {
    value: "Zanzibar South",
    label: "Zanzibar South",
    cities: ["Koani", "Koani Ndogo", "Mahonda", "Nganane", "Sokoni"],
  },
  { value: "Zanzibar West", label: "Zanzibar West", cities: ["Zanzibar"] },
];

// State Data for Tanzania  - used in Patient Profile

export const STATE_GHANA = [
  {
    value: "Ashanti",
    label: "Ashanti",
    cities: [
      "Kumasi",
      "Obuasi",
      "Tafo",
      "Ejura",
      "Nkawkaw",
      "Mampong",
      "Agogo",
      "Konongo",
      "Mpraeso",
      "Bekwai",
      "Abawe",
      "Abayisua",
      "Abease",
      "Abeasi",
      "Abejum",
      "Abene",
      "Abepawtia",
      "Abansua",
      "Abesewa",
      "Abetem",
      "Abetensu",
      "Abetensua",
      "Abetife",
      "Abetifi",
      "Abetim",
      "Abepotia",
      "Abanyaso",
      "Abanyasu",
      "Abase",
      "Abasi",
      "Abasua",
      "Abasuakuma",
      "Abasuapayin",
      "Abasukuma",
      "Abawdiem",
    ],
  },
  {
    value: "Brong-Ahafo",
    label: "Brong-Ahafo",
    cities: [
      "Sunyani",
      "Techiman",
      "Berekum",
      "Wenchi",
      "Kintampo",
      "Bechem",
      "Duayaw Nkwanta",
      "Acherensua",
      "Adabokrom",
      "Adadeem",
      "Adamasu",
      "Adamsu",
      "Adantia",
      "Adoe",
      "Adoi",
      "Adowakrom",
      "Adowkrom",
      "Aboabo Number 3",
      "Adroban",
      "Adruban",
      "Aduchwie",
      "Adugyansu Akomada",
      "Adujanso",
      "Adukwajokrom",
      "Adukwatukrom",
      "Adutwie",
      "Afrancho",
      "Afrantwo",
      "Adroba",
      "Aboabo Number 4",
      "Abodom",
      "Abonsrakurom",
      "Abonzerakrom",
      "Abrikaso",
      "Abudom",
    ],
  },
  {
    value: "Central",
    label: "Central",
    cities: [
      "Cape Coast",
      "Winneba",
      "Abankrampa",
      "Abamkwanmu",
      "Abamkwam",
      "Abakunkam",
      "Abakrampa",
      "Aboabo",
      "Abontsa",
      "Abonkwa",
      "Abonku",
      "Abonko",
      "Abol",
      "Aboenu",
      "Abodum",
      "Abodom",
      "Aboasi",
      "Aboase",
      "Aboano",
      "Abakanunkun",
      "Abirrikum",
      "Abin",
      "Abiadi Eshiem",
      "Aberesa",
      "Abensia",
      "Abenkrom",
      "Abekabum",
      "Abeka",
      "Abasa",
      "Abankrom",
      "Abeadzi-Domenosi",
      "Mumford",
      "Saltpond",
      "Apam",
      "Elmina",
      "Winneba",
    ],
  },
  {
    value: "Eastern",
    label: "Eastern",
    cities: ["Koforidua"],
  },
  {
    value: "Greater Accra",
    label: "Greater Accra",
    cities: ["Accra", "Akra"],
  },
  {
    value: "Northern",
    label: "Northern",
    cities: [
      "Tamale",
      "Yendi",
      "Savelugu",
      "Salaga",
      "Kpandae",
      "Addah",
      "Addah Fishing Village",
      "Addahyiri",
      "Adibo",
      "Aduyeli",
      "Aduyili",
      "Afumyinga",
      "Ajantudua",
      "Akaniem",
      "Akaratesi",
      "Akinajile",
      "Achinayili",
      "Akingayile",
      "Akorambala",
      "Akromabila Number 1",
      "Akromabila Number 2",
      "Akromabra",
      "Akumdipe",
      "Akunoyi",
      "Alfayili",
      "Alfayinga",
      "Ampedu",
      "Ando",
      "Akinayile",
      "Achinyile",
      "Ada",
      "Adare",
      "Adayiri",
    ],
  },
  {
    value: "Upper East",
    label: "Upper East",
    cities: [
      "Bawku",
      "Bolgatanga",
      "Navrongo",
      "Abilitega",
      "Abliri",
      "Acharaba",
      "Adaboya",
      "Adokobisi",
      "Adonsi",
      "Adoweko",
      "Adunania",
      "Adung",
      "Aeopea",
      "Agago",
      "Agushi",
      "Akamo",
      "Akanaba",
      "Abeu",
      "Akulmasa",
      "Akunda",
      "Akundaw",
      "Akundawi",
      "Akunduo",
      "Akunka",
      "Akunkogo",
      "Akunkongo",
      "Akunkongu",
      "Akure",
      "Akuri",
      "Alagiligobisi",
      "Alenzua",
      "Alidem",
      "Akorisi",
      "Abilatega",
      "Abileteiga",
    ],
  },
  {
    value: "Upper West",
    label: "Upper West",
    cities: [
      "Wa",
      "Arumon",
      "Baayiri",
      "Baazu",
      "Babile",
      "Babilli",
      "Babujan",
      "Babweasan",
      "Baghari",
      "Bagri",
      "Baire",
      "Bala",
      "Balafile",
      "Balie",
      "Bamkpoma",
      "Bandei",
      "Amburi",
      "Bangwon",
      "Banko",
      "Bankpama",
      "Banla",
      "Bano",
      "Banosan",
      "Bantala",
      "Banu",
      "Barewon",
      "Basabli",
      "Base",
      "Basebli",
      "Basiasan",
      "Basirisan",
      "Basisan",
      "Bawiesibal",
      "Bangmo",
    ],
  },
  {
    value: "Volta",
    label: "Volta",
    cities: [
      "Tema",
      "Teshie",
      "Nungua",
      "Madina",
      "Ho",
      "Hohoe",
      "Aflao",
      "Anloga",
      "Nsawam",
      "Suhum",
      "Begoro",
      "Kpandu",
      "Keta",
      "Aburi",
      "Akropong",
      "Ablibukope",
      "Ablibukorpe",
      "Abetia",
      "Ablonu",
      "Abluno",
      "Ablimen",
      "Abetinsi",
      "Abetinso",
      "Abia",
      "Abiriu",
      "Abiriw",
      "Ablajei",
      "Ablamuzadu",
      "Ablanfedo",
      "Ablefu",
      "Ablekpui",
      "Ablekuma",
      "Ablemkpe",
      "Ablenkpe",
      "Ablevenia",
    ],
  },
  {
    value: "Western",
    label: "Western",
    cities: [
      "Takoradi",
      "Sekondi",
      "Swedru",
      "Tarkwa",
      "Asamankese",
      "Oda",
      "Prestea",
      "Dunkwa",
      "Axim",
      "Shama",
      "Akwatia",
      "Bibiani",
      "Foso",
      "Kade",
      "Kibi",
      "Aboso",
      "Akim Swedru",
      "Abehu",
      "Abnabna",
      "Abem",
      "Abenakrom",
      "Abenase",
      "Abenasi",
      "Abenaso",
      "Abene",
      "Abeni",
      "Abenia",
      "Abepim",
      "Aberem",
      "Abetemasu",
      "Abiem",
      "Abirem",
      "Abirem Odumasi",
      "Abisim",
      "Ablabo",
    ],
  },
];

// Patient/Child disabilities -  used in Patient Profile
export const PATIENT_CHILDREN_DISABILITIES = [
  { value: "None", label: "none" },
  { value: "Vision impairment", label: "vision-impairment" },
  { value: "Deaf or hard of hearing", label: "deaf-or-hard-of-hearing" },
  { value: "Mental health conditions", label: "mental-health-conditions" },
  { value: "Intellectual disability", label: "intellectual-disability" },
  { value: "Acquired brain injury", label: "acquired-brain-injury" },
  { value: "Autism spectrum disorder", label: "autism-spectrum-disorder" },
  { value: "Physical disability", label: "physical-disability" },
];

// Child gender -  used in Patient Profile in modal
export const GENDER = [
  { value: "Male", label: "Male" },
  { value: "Female", label: "Female" },
  { value: "Non-binary", label: "Non-binary" },
  { value: "Prefer not to say", label: "Prefer not to say" },
];

// Patient/Child allergies -  used in Patient Profile
export const PATIENT_CHILDREN_ALLERGIES = [
  { value: "None", label: "none" },
  { value: "Drug allergy", label: "drug-allergy" },
  { value: "Food allergy", label: "food-allergy" },
  { value: "Insect allergy", label: "insect-allergy" },
  { value: "Latex allergy", label: "latex-allergy" },
  { value: "Mold allergy", label: "mold-allergy" },
  { value: "Pet allergy", label: "pet-allergy" },
  { value: "Pollen allergy", label: "pollen-allergy" },
  { value: "Skin allergy", label: "skin-allergy" },
  { value: "Dust allergies", label: "dust-allergies" },
  { value: "Eye allergy", label: "eye-allergy" },
  { value: "Insect sting allergies", label: "insect-sting-allergies" },
  { value: "Hay fever", label: "hay-fever" },
  { value: "Cockroach allergy", label: "cockroach-allergy" },
  { value: "Mold allergies", label: "mold-allergies" },
  { value: "Ragweed allergy", label: "ragweed-allergy" },
  { value: "Seasonal allergies", label: "seasonal-allergies" },
  { value: "Chlorine allery", label: "chlorine-allery" },
  { value: "Pine tree allergy", label: "pine-tree-allergy" },
  { value: "Eosinophilic esophagitis", label: "eosinophilic-esophagitis" },
];

// Patient Medical Problems - used in Patient Profile
export const PATIENT_MEDICAL_PROBLEMS = [
  "none",
  "abdominal-aortic-aneurysm",
  "abdominal-cramps",
  "abdominal-discomfort",
  "abdominal-pain",
  "acne",
  "acute-cholecystitis",
  "acute-lymphoblastic-leukaemia",
  "acute-lymphoblastic-leukaemia-children",
  "acute-lymphoblastic-leukaemia-teenagers-and-young-adults",
  "acute-myeloid-leukaemia",
  "acute-myeloid-leukaemia-children",
  "acute-myeloid-leukaemia-teenagers-and-young-adults",
  "acute-pancreatitis",
  "addisons-disease",
  "alcohol-related-liver-disease",
  "allergic-rhinitis",
  "allergies",
  "alzheimers-disease",
  "anal-cancer",
  "anaphylaxis",
  "angioedema",
  "ankylosing-spondylitis",
  "anorexia-nervosa",
  "anxiety",
  "anxiety-disorders-in-children",
  "appendicitis",
  "arthritis",
  "asbestosis",
  "asthma",
  "atopic-eczema",
  "attention-deficit-hyperactivity-disorder-adhd",
  "autistic-spectrum-disorder-asd",
  "bacterial-vaginosis",
  "benign-prostate-enlargement",
  "bile-duct-cancer-cholangiocarcinoma",
  "binge-eating",
  "bipolar-disorder",
  "bladder-cancer",
  "blood-poisoning-sepsis",
  "bone-cancer",
  "bone-cancer-teenagers-and-young-adults",
  "bowel-cancer",
  "bowel-incontinences",
  "bowel-polyps",
  "brain-stem-deathy",
  "brain-tumourss",
  "brain-tumours-children",
  "brain-tumours-teenagers-and-young-adults",
  "breast-cancer-female",
  "breast-cancer-male",
  "bronchiectasis",
  "bronchitis",
  "bulimia",
  "bunion",
  "carcinoid-syndrome-and-carcinoid-tumours",
  "catarrh",
  "cellulitis",
  "cervical-cancer",
  "chest-infection",
  "chest-pain",
  "chickenpox",
  "chilblains",
  "chlamydia",
  "chills",
  "chronic-fatigue-syndrome",
  "chronic-kidney-diseases",
  "chronic-lymphocytic-leukaemia",
  "chronic-myeloid-leukaemia",
  "chronic-obstructive-pulmonary-disease",
  "chronic-pancreatitis",
  "cirrhosis",
  "clostridium-difficile",
  "coeliac-disease",
  "cold-sore",
  "coma",
  "common-cold",
  "common-heart-conditions",
  "congenital-heart-disease",
  "conjunctivitis",
  "constipation",
  "coronavirus-covid-19",
  "cough",
  "crohns-disease",
  "croup",
  "cystic-fibrosis",
  "cystitis",
  "deafblindness",
  "deep-vein-thrombosis",
  "dehydration",
  "dementia",
  "dementia-with-lewy-bodies",
  "dental-abscess",
  "depression",
  "dermatitis-herpetiformis",
  "diabetes",
  "difficulty-in-breathing",
  "diarrhea",
  "discoid-eczema",
  "diverticular-disease-and-diverticulitis",
  "dizziness-lightheadedness",
  "downs-syndrome",
  "dry-mouth",
  "dysphagia-swallowing-problems",
  "dystonia",
  "ear-ache",
  "earwax-build-up",
  "ebola-virus-disease",
  "ectopic-pregnancy",
  "endometriosis",
  "epilepsy",
  "erectile-dysfunction-impotence",
  "escherichia-coli-e-coli-o157",
  "ewing-sarcoma",
  "ewing-sarcoma-children",
  "exudation-of-pus",
  "eye-cancer",
  "eye-irritation",
  "febrile-seizures",
  "fever",
  "fever-in-adults",
  "fever-in-children",
  "fibroids",
  "fibromyalgia",
  "flatulence",
  "flu",
  "foetal-alcohol-syndrome",
  "food-poisoning",
  "fungal-nail-infection",
  "gallbladder-cancer",
  "gallstones",
  "ganglion-cyst",
  "gastroenteritis",
  "gastro-oesophageal-reflux-disease-gord",
  "genital-herpes",
  "genital-warts",
  "germ-cell-tumours",
  "glandular-fever",
  "gonorrhoea",
  "gout",
  "gum-disease",
  "haemorrhoids-piles",
  "hairy-cell-leukaemia",
  "hand-foot-and-mouth-disease",
  "hay-fever",
  "head-and-neck-cancer",
  "head-lice-and-nits",
  "headaches",
  "hearing-loss",
  "heart-failure",
  "hepatitis-a",
  "hepatitis-b",
  "hepatitis-c",
  "hiatus-hernia",
  "high-cholesterol",
  "hiv",
  "hodgkin-lymphoma",
  "hodgkin-lymphoma-children",
  "hodgkin-lymphoma-teenagers-and-young-adults",
  "huntingtons-disease",
  "hyperglycaemia-high-blood-sugar",
  "hyperhidrosis",
  "hypoglycaemia-low-blood-sugar",
  "idiopathic-pulmonary-fibrosis",
  "indigestion",
  "ingrown-toenail",
  "inherited-heart-conditions",
  "insomnia",
  "iron-deficiency-anaemia",
  "irritable-bowel-syndrome-ibs",
  "irritable-hip",
  "itching",
  "itchy-bottom",
  "kaposis-sarcoma",
  "impetigo",
  "kidney-cancer",
  "kidney-infection",
  "kidney-stones",
  "labyrinthitis",
  "lactose-intolerance",
  "langerhans-cell-histiocytosis",
  "laryngeal-larynx-cancer",
  "laryngitis",
  "leg-cramps",
  "lichen-planus",
  "liver-cancer",
  "liver-disease",
  "liver-tumours",
  "loss-of-libido",
  "lung-cancer",
  "lupus",
  "lyme-disease",
  "lymphoedema",
  "lymphogranuloma-venereum-lgv",
  "malaria",
  "malignant-brain-tumour-cancerous",
  "malnutrition",
  "measles",
  "meningitis",
  "menopause",
  "mesothelioma",
  "middle-ear-infection-otitis-media",
  "migraine",
  "miscarriage",
  "motor-neurone-disease-mnd",
  "mouth-cancer",
  "mouth-ulcer",
  "multiple-myeloma",
  "multiple-sclerosis-ms",
  "mumps",
  "menieres-disease",
  "nasal-and-sinus-cancer",
  "nasopharyngeal-cancer",
  "neuroblastoma",
  "neuroblastoma-children",
  "neuroendocrine-tumours",
  "noisy-breathing",
  "non-alcoholic-fatty-liver-disease-nafld",
  "non-hodgkin-lymphoma",
  "non-hodgkin-lymphoma-children",
  "norovirus",
  "nosebleed",
  "obesity",
  "obsessive-compulsive-disorder-ocd",
  "obstructive-sleep-apnoea",
  "oesophageal-cancer",
  "oral-thrush-in-adults",
  "osteoarthritis",
  "osteoporosis",
  "osteosarcoma",
  "otitis-externa",
  "ovarian-cancer",
  "ovarian-cancer-teenagers-and-young-adults",
  "ovarian-cyst",
  "overactive-thyroid",
  "pagets-disease-of-the-nipple",
  "palpitations",
  "pancreatic-cancer",
  "panic-disorder",
  "parkinsons-disease",
  "pelvic-discomfort",
  "pelvic-inflammatory-disease",
  "pelvic-organ-prolapse",
  "pelvic-pain",
  "pelvic-pressure",
  "penile-cancer",
  "peripheral-neuropathy",
  "personality-disorder",
  "pink-eye",
  "pleurisy",
  "pneumonia",
  "polymyalgia-rheumatica",
  "post-traumatic-stress-disorder-ptsd",
  "postnatal-depression",
  "pregnancy-and-baby",
  "pressure-ulcers",
  "prostate-cancer",
  "psoriasis",
  "psoriatic-arthritis",
  "psychosis",
  "pubic-lice",
  "rare-tumours",
  "rashes",
  "raynauds-phenomenon",
  "reactive-arthritis",
  "restless-legs-syndrome",
  "retinoblastoma",
  "retinoblastoma-children",
  "rhabdomyosarcoma",
  "rheumatoid-arthritis",
  "ringing-ears",
  "ringworm-and-other-fungal-infections",
  "rosacea",
  "scabies",
  "scarlet-fever",
  "schizophrenia",
  "scoliosis",
  "septic-shock",
  "shingles",
  "shortness-of-breath",
  "sickle-cell-disease",
  "sinusitis",
  "sjogrens-syndrome",
  "skin-cancer-melanoma",
  "skin-cancer-non-melanoma",
  "slapped-cheek-syndrome",
  "soft-tissue-sarcomas",
  "soft-tissue-sarcomas-teenagers-and-young-adults",
  "sore-throat",
  "spleen-problems-and-spleen-removal",
  "stillbirth",
  "stomach-ache-and-abdominal-pain",
  "stomach-cancer",
  "stomach-ulcer",
  "stress-anxiety-and-low-mood",
  "stroke",
  "sudden-infant-death-syndrome-sids",
  "suicide",
  "sunburn",
  "swollen-glands",
  "syphilis",
  "tachypnea",
  "testicular-cancer",
  "testicular-cancer-teenagers-and-young-adults",
  "testicular-lumps-and-swellings",
  "thirst",
  "threadworms",
  "thrush",
  "thrush-in-men",
  "thyroid-cancer",
  "thyroid-cancer-teenagers-and-young-adults",
  "tinnitus",
  "tonsillitis",
  "tooth-decay",
  "toothache",
  "transient-ischaemic-attack-tia",
  "trigeminal-neuralgia",
  "tuberculosis-tb",
  "type-1-diabetes",
  "type-2-diabetes",
  "trichomonas-infection",
  "ulcerative-colitis",
  "underactive-thyroid",
  "urinary-incontinence",
  "urinary-tract-infection-uti",
  "urinary-tract-infection-uti-in-children",
  "urticaria-hives",
  "vaginal-cancer",
  "vaginal-thrush",
  "varicose-eczema",
  "venous-leg-ulcer",
  "vertigo",
  "vitamin-b12-or-folate-deficiency-anaemia",
  "vomiting-in-adults",
  "vulval-cancer",
  "warts-and-verrucas",
  "whooping-cough",
  "wilms-tumour",
  "womb-uterus-cancer",
  "yellow-fever",
];
