name: Create Branch Image

on:
  repository_dispatch:
    types: [trigger-admin-portal]
  workflow_dispatch:
    inputs:
      target-branch:
        description: 'Target Branch'
        required: true
        default: 'oracle-test'
      NEXT_PUBLIC_API_URL_VAR:
        description: 'Value for NEXT_PUBLIC_API_URL_VAR'
        required: true
      NEXT_PUBLIC_DOMAIN_VAR:
        description: 'Value for NEXT_PUBLIC_DOMAIN_VAR'
        required: true
      NEXT_PUBLIC_LOGIN_URL_VAR:
        description: 'Value for NEXT_PUBLIC_LOGIN_URL_VAR'
        required: true
      NEXT_PUBLIC_COUNTRY_CODE:
        description: 'Value for NEXT_PUBLIC_COUNTRY_CODE'
        required: true
      NODE_ENV:
        description: 'Value for NODE_ENV'
        required: true
      NAME:
        description: 'Value for NAME'
        required: true

env:
  REGISTRY: https://registry.hub.docker.com/v2/
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  build-and-push:
    runs-on: self-hosted
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      #- name: Log in to the Container registry
      #  run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      #- name: Extract metadata (tags, labels) for Docker
      #  id: meta
      #  uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      #  with:
      #    images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
     
      #- name: Create env variables
      #  run: |
      #    chmod +x ./env.example.sh
      #    ./env.example.sh
      #    cat .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check if Docker Buildx builder exists
        id: check_builder
        run: |
          if docker buildx inspect mybuilder &> /dev/null; then
            echo "builder_exists=true" >> $GITHUB_OUTPUT
          else
            echo "builder_exists=false" >> $GITHUB_OUTPUT
          fi
      - name: Create a Docker Buildx builder if it doesn't exist
        if: steps.check_builder.outputs.builder_exists == 'false'
        run: |
          docker buildx create --use --name mybuilder
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: "swedcon18com/carelyo:${{ inputs.NAME }}-admin"
          file: Dockerfile
          builder: mybuilder
          build-args: |
              NEXT_PUBLIC_API_URL_VAR=${{ inputs.NEXT_PUBLIC_API_URL_VAR }}
              NEXT_PUBLIC_DOMAIN_VAR=${{ inputs.NEXT_PUBLIC_DOMAIN_VAR }}
              NEXT_PUBLIC_LOGIN_URL_VAR=${{ inputs.NEXT_PUBLIC_LOGIN_URL_VAR }}
              NEXT_PUBLIC_COUNTRY_CODE=${{ inputs.NEXT_PUBLIC_COUNTRY_CODE }}
              NODE_ENV=${{ inputs.NODE_ENV }}
              NAME=${{ inputs.NAME }}
