package com.carelyo.v1.enums;

public enum ETemplateTypes {
  BASE_TEMPLATE,
  BOOKED_CONSULTATION_PATIENT,
  NEW_CONSULTATION_AVAILABLE_DOCTOR,
  FAILED_PAYMENT_NO_BOOKING,
  CANCEL_CONSULTATION_PATIENT,
  CANCEL_CONSULTATION_DOCTOR,
  DOCTOR_ACCEPT_CONSULTATION,
  DOCTOR_STARTED_CONSULTATION,
  FOLLOWUP_BOOKED,
  FOLLOWUP_REMINDER,
  NOTIFICATION,
  PASSWORD_RESET,
  PASSWORD_RESET_FAILED,
  PROVIDER_UPDATED,
  USER_DETAILS_UPDATED,
  USER_INVITATION,
  WELCOME_MESSAGE_DOCTOR,
  WELCOME_MESSAGE_PATIENT,
}
