name: Build & Push To DockerHub

on:
  push:
    branches:
      - develop
      - staging
      - production

jobs:
  rename-and-build:
    runs-on: self-hosted
    steps:
      - name: Get branch name
        id: branch_name
        run: | 
          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Pull Docker image
        env:
          BRANCH_NAME: ${{ env.BRANCH_NAME }}
        run: docker pull swedcon18com/carelyo:care-patient-portal-${{ env.BRANCH_NAME }}-latest
      
      - name: Get current image version
        run: |
          CURRENT_VERSION=$(docker inspect --format='{{ index .RepoDigests 0 }}' swedcon18com/carelyo:care-patient-portal-${{ env.BRANCH_NAME }}-latest | awk -F':' '{print $3}')
          NEXT_VERSION=$((CURRENT_VERSION + 1))
          echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_ENV
      
      - name: Read updated version number
        run: echo "${{ env.NEXT_VERSION }}" > version.txt
      
      - name: Rename Docker image
        run: |
          docker tag swedcon18com/carelyo:care-patient-portal-${{ env.BRANCH_NAME }}-latest swedcon18com/carelyo:care-patient-portal-${{ env.BRANCH_NAME }}-${{ env.NEXT_VERSION }}
      
      - name: Push renamed image
        run: docker push swedcon18com/carelyo:care-patient-portal-${{ env.BRANCH_NAME }}-${{ env.NEXT_VERSION }}
        
  build-and-publish:
    runs-on: self-hosted
    steps:
      - name: Remove unnecessary files
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Get branch name
        id: branch_name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and Push Docker Image
        env:
          BRANCH_NAME: ${{ env.BRANCH_NAME }}
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/arm64
          tags: "swedcon18com/carelyo:care-patient-portal-${{ env.BRANCH_NAME }}-latest"
          cache-from: type=gha
          cache-to: type=gha,mode=max
