name: Create Branch Image

on:
  repository_dispatch:
    types: [trigger-care-patient-test]
  workflow_dispatch:
    inputs:
      target-branch:
        description: 'Target Branch'
        required: true
        default: 'oracle-test'
      VITE_API_URL_VAR:
        description: 'Value for VITE_API_URL_VAR'
        required: true
      VITE_DEBUG_SLEEP_VAR:
        description: 'Value for VITE_DEBUG_SLEEP_VAR'
        required: true
      VITE_DEBUG_SLEEP_TIME_MS_VAR:
        description: 'Value for VITE_DOCTOR_URL_VAR'
        required: true
      VITE_GLITCH_DNS_VAR:
        description: 'Value for VITE_GLITCH_DNS_VAR'
        required: true
      VITE_POLLING_RATE_VAR:
        description: 'Value for VITE_POLLING_RATE_VAR'
        required: true
      VITE_LOGIN_URL_VAR:
        description: 'Value for VITE_LOGIN_URL_VAR'
        required: true


env:
  REGISTRY: https://registry.hub.docker.com/v2/
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  build-and-push:
    runs-on: self-hosted
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      #- name: Set up QEMU
        #uses: docker/setup-qemu-action@v1

      #- name: Create env variables
      #  run: |
       #   chmod +x ./env.example.sh
        #  ./env.example.sh

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      
      - name: Check if Docker Buildx builder exists
        run: |
          if docker buildx inspect mybuilder &> /dev/null; then
            echo "Docker Buildx builder 'mybuilder' already exists."
            exit 0
          else
            echo "Docker Buildx builder 'mybuilder' does not exist."
            exit 1
          fi
      
      - name: Create a Docker Buildx builder if it doesn't exist
        if: ${{ failure() }}
        run: |
          docker buildx create --use --name mybuilder

      #- name: Create a Docker Buildx builder
      #  run: |
      #    docker buildx create --use --name mybuilder

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          platforms: linux/arm64,linux/amd64
          tags: swedcon18com/carelyo:care-portal-test-latest
          file: Dockerfile
          builder: mybuilder
          build-args: |
              PORT_VAR="3122"
              VITE_API_URL_VAR=${{ inputs.VITE_API_URL_VAR }}
              VITE_DEBUG_SLEEP_VAR=${{ inputs.VITE_DEBUG_SLEEP_VAR }}
              VITE_DEBUG_SLEEP_TIME_MS_VAR=${{ inputs.VITE_DEBUG_SLEEP_TIME_MS_VAR }}
              VITE_GLITCH_DNS_VAR=${{ inputs.VITE_GLITCH_DNS_VAR }}
              VITE_POLLING_RATE_VAR=${{ inputs.VITE_POLLING_RATE_VAR }}
              VITE_LOGIN_URL_VAR=${{ inputs.VITE_LOGIN_URL_VAR }}